name: Nix CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  all-in-one:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v27

      - name: Check Nix syntax
        run: |
          set -eu
          nix-instantiate --parse home.nix

      - name: Check Home Manager config builds
        run: |
          set -eu
          nix-channel --add https://nixos.org/channels/nixpkgs-25.05-darwin nixpkgs
          nix-channel --add https://github.com/nix-community/home-manager/archive/release-25.05.tar.gz home-manager
          nix-channel --update
          nix-shell '<home-manager>' -A install
          home-manager build -f ./home.nix

      - name: Check Nix formatting
        run: |
          set -eu
          nix-env -iA nixpkgs.nixpkgs-fmt
          nixpkgs-fmt --check home.nix
