name: Nix CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check-nix:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v27

      - name: Check Nix syntax
        run: |
          # Use set -eu, not pipefail, for best compatibility in CI
          set -eu
          nix-instantiate --parse home.nix
